### ISSUE TITLE
Piplup Image Incorrect

### ISSUE THREAD

**Issue by zettu** [MikeTheShadow/PokeCordBot#1]
The image for piplup is incorrect, it says to download the image from the "sidebar" on bulbapedia but when i go to the piplup page the only image available isn't the correct resolution. I updated with image from discord though.
Thank you very much for this! Maybe i can finally have some half decent pokemon.
I'd also suggest removing it violates Discord's tos and put something more ambiguous, I'm not sure of github would take it down though so maybe doesn't matter @MikeTheShadow

**Comment by MikeTheShadow** [comment]
Thanks I fixed it in the source. There are other pokemon that are missing just fyi and some might be wrong. Idk how that one messed up lol

**Comment by zettu** [comment]
Aweome, I'll post any i find missing if it helps :)

**Comment by zettu** [comment]
> 
> 
> Thanks I fixed it in the source. There are other pokemon that are missing just fyi and some might be wrong. Idk how that one messed up lol

The bulbapedia image for piplup isn't the same as the pokecord one.
