### ISSUE TITLE
Will adding the images from discord link of a spawn to the pokedex work?

### ISSUE THREAD

**Issue by zettu** [MikeTheShadow/PokeCordBot#15]
Will adding the images from discord link of a spawn to the pokedex work? @MikeTheShadow

**Comment by MikeTheShadow** [comment]
download it directly from source and add it to the folder delete the .dat and rerun will recreate the file. It will add all the new ones in the pokedex folder to the dat

**Comment by zettu** [comment]
> 
> 
> download it directly from source and add it to the folder delete the .dat and rerun will recreate the file. It will add all the new ones in the pokedex folder to the dat

by source you mean the discord attachment link it generates? that's what i've been doing everytime one errors but i have yet to have a repeat of an errored poke so wasnt sure. i uploaded the discord attachment link and names to all that havent worked so far :) tyyyyyyy

**Comment by MikeTheShadow** [comment]
Np please use this thread for all other missing pokemon to prevent spam thanks @zettu

**Comment by MikeTheShadow** [comment]
And yes the source image is the "open original" one

**Comment by zettu** [comment]
> 
> 
> And yes the source image is the "open original" one

I get the option to "open link" in discord which takes me straight to a page with the image and no "open original" option, is downloading from this page correct? @MikeTheShadow 
Ok i'll post all ones in a new comment with the the link above if you confirm that's the correct method.
I posted the link also in all the new issues i had made before. sorry, i didn't mean to clutter it and thought a new one for each would be better. again tyyy, im trying to help and will post every pokemon that doesn't work!

**Comment by MikeTheShadow** [comment]
https://cdn.discordapp.com/attachments/593880793311608834/594262361381273610/unknown.png this is the button on the desktop version you want the source image as discord can mess with image sizes and yeah if you open the link that should work.

**Comment by zettu** [comment]
> 
> 
> https://cdn.discordapp.com/attachments/593880793311608834/594262361381273610/unknown.png this is the button on the desktop version you want the source image as discord can mess with image sizes and yeah if you open the link that should work.

ok yea, i wasn't clicking open original i was using the the 3 dot menu to open link, though both options take you to the exact same link -- at least on the few i just tried. thank you :)

**Comment by MikeTheShadow** [comment]
@zettu please use the new issue [here](https://github.com/MikeTheShadow/PokeCordBot/issues/16) to report missing/wrong pokemon thanks!
