### ISSUE TITLE
PUT ALL MISSING POKEMON HERE!

### ISSUE THREAD

**Issue by MikeTheShadow** [MikeTheShadow/PokeCordBot#16]
Any missing pokemon should be added here like the one below Please include name and make sure they are the .jpg format thanks!
![Abomasnow](https://user-images.githubusercontent.com/18271009/60376431-297dd000-99cc-11e9-88af-d71ad5647f07.jpg)

**Comment by zettu** [comment]
Incorrect image for Chimchar
https://cdn.discordapp.com/attachments/586707416398168072/594311125605154816/PokecordSpawn.jpg
![Chimchar](https://user-images.githubusercontent.com/52323898/60376760-0ad50480-99df-11e9-82cf-083f75f3f285.jpg)

**Comment by zettu** [comment]
Salandit
![Salandit](https://user-images.githubusercontent.com/52323898/60376900-b67e5480-99df-11e9-9049-368285f9405a.jpg)

**Comment by zettu** [comment]
@MikeTheShadow do i need to redo all the ones from the tickets you closed?

**Comment by MikeTheShadow** [comment]
Closed means I've added them

**Comment by zettu** [comment]
> 
> 
> Closed means I've added them
aight, was just checking before i uploaded all 15 or whatever of those too lol

**Comment by MikeTheShadow** [comment]
If you can. Make a zip with all the pokemon named properly that would help a bit too

**Comment by zettu** [comment]
> 
> 
> If you can. Make a zip with all the pokemon named properly that would help a bit too

make a .zip of each individual pokemon or zip of all off the missing pokemon the upload in batch like once a day?

**Comment by zettu** [comment]
Gumshoos
![Gumshoos](https://user-images.githubusercontent.com/52323898/60377340-ddd72080-99e3-11e9-9791-5e70232a7985.jpg)
[Gumshoos.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3341225/Gumshoos.zip)

**Comment by MikeTheShadow** [comment]
if you find a bunch just name and zip em

**Comment by zettu** [comment]
Missing Fomantis
[Fomantis.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3341269/Fomantis.zip)
![Fomantis](https://user-images.githubusercontent.com/52323898/60378060-bd5e9480-99ea-11e9-9f78-d3a8d892c2a7.jpg)
https://cdn.discordapp.com/attachments/586707416398168072/594333779242516503/PokecordSpawn.jpg

**Comment by zettu** [comment]
Missing Yungoos
[Yungoos.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3341298/Yungoos.zip)
![Yungoos](https://user-images.githubusercontent.com/52323898/60378403-2399e600-99f0-11e9-9cad-48d9c9313bab.jpg)
https://cdn.discordapp.com/attachments/586707416398168072/594343879289995284/PokecordSpawn.jpg

**Comment by zettu** [comment]
It took an hour but finally got all alolans lol
[All 18 Alolans.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3341319/All.18.Alolans.zip)

**Comment by MikeTheShadow** [comment]
Added

**Comment by zettu** [comment]
Basculin image incorrect
[Basculin.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3341893/Basculin.zip)
Unfezant image incorrect
[Unfezant.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3341899/Unfezant.zip)

**Comment by zettu** [comment]
Missing Shiinotic
[Shiinotic.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3342055/Shiinotic.zip)
![Shiinotic](https://user-images.githubusercontent.com/52323898/60386592-ed4a7e00-9a64-11e9-8262-8555d6f5ea11.png)

**Comment by zettu** [comment]
took several hours but i went through and added all the remaining missing pokemon, at least i think. also corrected a few. this doesn't include any i've uploaded already. however it does include typenull named TypeNull just in case lol. has some good pokes in it
i'll go through later and make sure all myth, ubs, and lege are correct
[i think this is all of the pokemon that were missing, also some that were incorrect.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3342208/i.think.this.is.all.of.the.pokemon.that.were.missing.also.some.that.were.incorrect.zip)
@MikeTheShadow

**Comment by zettu** [comment]
Damn we're at 826 now but there are 827 counting alolans. so we're missing one, is there any way to find out which it is without me going back over each one individually lol

**Comment by MikeTheShadow** [comment]
We're at 827 now. The only issue will be image mismatches I will upload the new pokedex shortly you can download it from the source if youd like.

**Comment by zettu** [comment]
@MikeTheShadow in the source you didn't update the basculin i added, the original basculin was incorrect (mismatches).
also does the source have the ones from the zip i attached above cause that had a few that were incorrect

**Comment by MikeTheShadow** [comment]
yes it does

**Comment by zettu** [comment]
here's the correct basculin again, i think it was maybe missed cause i only uploaded zip for it. my bad lol.
Also not really a missing pokemon but tsareena and trumbeak aren't capitalized in the source.
![Basculin](https://user-images.githubusercontent.com/52323898/60389020-29430a80-9a88-11e9-8231-85ca69e084f2.jpg)

**Comment by zettu** [comment]
> 
> 
> yes it does

also all the alolans in the source are all pngs while everything else is jpg, i'm not sure if i uploaded em as pngs. @MikeTheShadow

**Comment by MikeTheShadow** [comment]
you did I fixed them

**Comment by zettu** [comment]
> 
> 
> you did I fixed them
Mewostic image is incorrect
[Meowstic.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3342333/Meowstic.zip)
https://cdn.discordapp.com/attachments/586707416398168072/594640812399132687/PokecordSpawn.jpg
![Meowstic](https://user-images.githubusercontent.com/52323898/60389754-737eb880-9a95-11e9-9175-f3c58b2c3d51.jpg)

**Comment by MikeTheShadow** [comment]
added

**Comment by zettu** [comment]
> 
> 
> added
Snivy image incorrect
[Snivy.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3347627/Snivy.zip)
https://cdn.discordapp.com/attachments/586707416398168072/595382633051979783/PokecordSpawn.jpg
![Snivy](https://user-images.githubusercontent.com/52323898/60471977-fd18bc80-9c34-11e9-9175-c6865519be02.jpg)

**Comment by zettu** [comment]
Pyroar image resolution incorrect

**Comment by zettu** [comment]
Mudkip image incorrect
[Mudkip.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3357337/Mudkip.zip)
![Mudkip](https://user-images.githubusercontent.com/52323898/60634959-e9a95500-9dde-11e9-8760-47805df1bef6.jpg)

**Comment by zettu** [comment]
Torchic image incorrect
[Torchic.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3360378/Torchic.zip)
![Torchic](https://user-images.githubusercontent.com/52323898/60686191-625af080-9e75-11e9-813e-0e81b1bd7601.jpg)

**Comment by zettu** [comment]
Treecko image incorrect
[Treecko.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3360381/Treecko.zip)
![Treecko](https://user-images.githubusercontent.com/52323898/60686318-017fe800-9e76-11e9-8c74-13963f34d7b0.jpg)

**Comment by zettu** [comment]
Tepig image incorrect
[Tepig.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3360396/Tepig.zip)
![Uploading Tepig.jpg…]()

**Comment by zettu** [comment]
Klefki image wrong resolution.
[Klefki.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3360744/Klefki.zip)
![Klefki](https://user-images.githubusercontent.com/52323898/60691441-a366fb00-9e9d-11e9-9f92-e9fba082d384.jpg)

**Comment by zettu** [comment]
Giratina incorrect 
[Giratina.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3366103/Giratina.zip)
![Giratina](https://user-images.githubusercontent.com/52323898/60773703-1b6c3580-a0d7-11e9-9ce8-da23e3f1384e.jpg)

**Comment by MikeTheShadow** [comment]
added.
