### ISSUE TITLE
Missing Option

### ISSUE THREAD

**Issue by zettu** [MikeTheShadow/PokeCordBot#17]
The option to enable spam (send messages) isn't in the program, you have to edit in the properties file. 
On a side note why is catch everything not recommended while using in your own private channel?
Also these are features I'd like to suggest:
Bulk trade pokemon to another account.
Change server prefix.
Ability to send multiple text phrases instead of one.

**Comment by MikeTheShadow** [comment]
I should probably rename it but search for pokemon is the spam option

**Comment by MikeTheShadow** [comment]
As for the other features I have a backlog of ideas but I'll add them to my consideration list
