### ISSUE TITLE
Unknown pokemon error for all pokemon in new version, 1.0.1

### ISSUE THREAD

**Issue by zettu** [MikeTheShadow/PokeCordBot#18]
Unknown pokemon error for all pokemon in new version, 1.0.1
This happens for all pokemon and i've regenerated dex and extracted the program again.

**Comment by MikeTheShadow** [comment]
damn lemme check lol

**Comment by MikeTheShadow** [comment]
this is going to take a while to debug just use the old version for now

**Comment by MikeTheShadow** [comment]
Should be patched in 1.0.2

**Comment by zettu** [comment]
> 
> 
> Should be patched in 1.0.2

@MikeTheShadow yep, is working for me, thank you!!!
on a side note the jpg file has never opened for me, why is this?

**Comment by MikeTheShadow** [comment]
which jpg file @zettu?

**Comment by zettu** [comment]
> 
> 
> which jpg file @zettu?

661829.jpg is the file name in the unknow folder, it's an empty file.

**Comment by MikeTheShadow** [comment]
That means it didnt write it properly. Im going to rewrite the unkown pokemon function to give a url link to the image rather than the image itself
