### ISSUE TITLE
Show the catch message?

### ISSUE THREAD

**Issue by CookiePl0x** [MikeTheShadow/PokeCordBot#19]
Is it possible to make the bot show the message used to catch the Pokemon? 

I.e. p!catch Pikachu

It seems kind of suspicious, when it just says caught the Pokemon, but there is no message indicating that you even attempted it.

Thanks in advance!

**Comment by zettu** [comment]
@CookiePl0x it shows the catch message for me, on my end at least.
Also is version 1.0.1 working for you or are you using version 1.0.0. the downloaded zip will say the version?

**Comment by CookiePl0x** [comment]
Strange, this is all I can see. 
![image](https://user-images.githubusercontent.com/13744383/60384785-791ed300-9a82-11e9-9d76-dd997cb7b362.png)

Not sure if this is relevant anymore, but the zip says 1.0.2

**Comment by CookiePl0x** [comment]
Nevermind, I fixed it. It was something stupid on my end with Betterdiscord.

**Comment by zettu** [comment]
> 
> 
> Nevermind, I fixed it. It was something stupid on my end with Betterdiscord.
> 
> Sorry about that. x-x
@CookiePl0x 
what exactly was it that was the issue and what fixed it? Just out of curiosity 
i was thinking maybe the realistic catch option was the issue.

**Comment by CookiePl0x** [comment]
Oh no, there is that thing called "BetterDiscord" which you can use to add usermade plugins and stuff to Discord. I just had something on that hides it.

But now a new error has come up, I tried the bot on a test account first. Now I wanted to use it on my main account, but it seems like several servers i'm in, is causing errors and makes it unable to run.

![image](https://user-images.githubusercontent.com/13744383/60385258-a91ca500-9a87-11e9-82d0-83c2e95d9db4.png)

**Comment by zettu** [comment]
> 
> 
> Oh no, there is that thing called "BetterDiscord" which you can use to add usermade plugins and stuff to Discord. I just had something on that hides it. The messages were actually there after I removed it.
> 
> But now a new error has come up, I tried the bot on a test account first. Now I wanted to use it on my main account, but it seems like several servers i'm in, is causing errors and makes it unable to run.
> 
> ![image](https://user-images.githubusercontent.com/13744383/60385258-a91ca500-9a87-11e9-82d0-83c2e95d9db4.png)

I don't know about the error you're having @MikeTheShadow is the maintainer and can hopefully help there but i just wanted to say I'd strongly suggest not doing this on your main account!

**Comment by CookiePl0x** [comment]
I suppose it's not safe then? I solely wanted to use it to catch some pokemon every now and then. Not the spammer or anything.

**Comment by zettu** [comment]
> 
> 
> I suppose it's not safe then? I solely wanted to use it to catch some pokemon every now and then. Not the spammer or anything.

it can get your dc acc banned so is better to use an alt.

**Comment by CookiePl0x** [comment]
>

> 
> 
> > I suppose it's not safe then? I solely wanted to use it to catch some pokemon every now and then. Not the spammer or anything.
> 
> it can get your dc acc banned so is better to use an alt.


Oh dear, I will better leave it be then. Well thank you regardless.

**Comment by MikeTheShadow** [comment]
Hmmmm I've never seen that error before. I would just use an account that has pokecord/you in the server and thats it to prevent issues with other discord. If that doesnt work I will need you to download custom versions to confirm this error

**Comment by MikeTheShadow** [comment]
Will be patched in V1.0.3 @CookiePl0x
