### ISSUE TITLE
Type: Null issue, details included

### ISSUE THREAD

**Issue by zettu** [MikeTheShadow/PokeCordBot#20]
i'm going throughall missing pokemon and adding them but can't add type: null because it has a colon, is there anyway we can name the file type null but have it output the catch as type: null
![Type Null](https://user-images.githubusercontent.com/52323898/60386783-ba55b980-9a67-11e9-957a-d5776a8a65e9.jpg)

**Comment by MikeTheShadow** [comment]
Renamed pokemon via code should work now. Default name is typenull and is changed to type: null in code
