### ISSUE TITLE
Caused pc to crash.

### ISSUE THREAD

**Issue by zettu** [MikeTheShadow/PokeCordBot#21]
Yesterday after leaving it running for several hours i came back and moved my mouse to wake the screen and started checking out the pokemon but there was tremendous system wide lag and my computer black screened. I left it for about 5 minutes came back and just had to pull the plug.
The only thing else open was a browser and stuff like this is abnormal. It's not a spec issue either.
Oh and another thing i didn't think much of till now, yesterday i noticed the bot was sending messages about twice as fast as normal so i stopped bot but the messages didn't stop so i just exited out of the bot, they stopped then.
I don't see a logs file anywhere or I would've uploaded with this, sorry.

**Comment by zettu** [comment]
the thing happened again with the bot not shutting down when i click stop and continuing to spam and catch just now, it appeared to be sending everything double at the end, it even found the same pokemon twice and tried to catch it twice, maybe because i clicked start a second time and it never stopped.
image of the issue and as you can see its not stopping even i click stop. sorry i can't provide much more to help
![pokebot](https://user-images.githubusercontent.com/52323898/60399702-c8264000-9b36-11e9-9891-9f2e962e42d0.PNG)

**Comment by MikeTheShadow** [comment]
Looking into this

**Comment by zettu** [comment]
> 
> 
> Looking into this

kk, if there's anything i can do to help just let me know. The bot is running fine right now, i think it not stopping and my pc crash were probably related.

**Comment by MikeTheShadow** [comment]
Stop is broken in this version will be patched in 1.0.4

**Comment by zettu** [comment]
> 
> 
> Stop is broken in this version will be patched in 1.0.4

what about it double sending messages and trying to catch 2x? is that from clicking start twice even though it never stopped?

**Comment by MikeTheShadow** [comment]
Thats because the bot was started twice due to a bug with the bot not stopping

**Comment by MikeTheShadow** [comment]
I've looked into the system usage bug but I cannot find anything that would increase resource usage @zettu I've added 1.0.4 and suggest you see if that fixes the problem.

**Comment by zettu** [comment]
> 
> 
> I've looked into the system usage bug but I cannot find anything that would increase resource usage @zettu I've added 1.0.4 and suggest you see if that fixes the problem.

kk, once the new version has ran for a long time i'll let you know whether that happens again. thank you!!!!

**Comment by zettu** [comment]
> 
> 
> I've looked into the system usage bug but I cannot find anything that would increase resource usage @zettu I've added 1.0.4 and suggest you see if that fixes the problem.

seems to be fine now, i'll let you know if something changes. oh found another poke but i'll post that on the right place @MikeTheShadow also i commented in the latest closed thread cause was slightly confused.

**Comment by zettu** [comment]
> 
> 
> Thats because the bot was started twice due to a bug with the bot not stopping

yea iy's fine now @MikeTheShadow ty
