### ISSUE TITLE
Debug dex size repeating in log.

### ISSUE THREAD

**Issue by zettu** [MikeTheShadow/PokeCordBot#22]
In the log "debug dex size" keeps repeating.
Also loading bar is a great addition imo lol.
Stop button working fine now in latest version tysm.
Could i make request for a user facing option to change spam char speed and catch speed lol. not needed though really and what it is now is probably what i'd leave it at
![pokebot](https://user-images.githubusercontent.com/52323898/60406253-f2055400-9b82-11e9-9993-da88a664eb74.JPG)

**Comment by MikeTheShadow** [comment]
fixed added to 1.0.4

**Comment by zettu** [comment]
> 
> 
> fixed added to 1.0.4

Do you mean 1.0.5, i redownloaded 1.0.5 from the link but it had the same issue @MikeTheShadow
