### ISSUE TITLE
How to change prefix being used

### ISSUE THREAD

**Issue by goldenisadrian** [MikeTheShadow/PokeCordBot#23]
Is there a way to or will there be a way to change the prefix that the bot will send

**Comment by zettu** [comment]
> 
> 
> Is there a way to or will there be a way to change the prefix that the bot will send

There currently isn't i user accessible option to do so.

**Comment by MikeTheShadow** [comment]
Added @goldenisadrian @zettu in 1.0.5 issue closed.
