### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by zettu** [MikeTheShadow/PokeCordBot#24]
I would like to suggest for the time out that you can select what hours of the day the bot will run. like youd click 1, 2, 3, 18, 20, 24, etc for the hours of the day you wanted it to run. I feel this,along with configurable spam/catch delays will help in detection evasion
Also i think an option for auto leveling your non-max favorited pokemon would be an amazing feature if possible!

**Comment by zettu** [comment]
Also this is unrelated but does catch everything mean catch all pokemon in all servers or catch all pokemon... cause it tried to catch in a different server in a channel i didn't configure

**Comment by MikeTheShadow** [comment]
Catch everything everywhere means that it will catch any pokemon in any channel

**Comment by goldenisadrian** [comment]
Some features I can think of:
Add an option to modify catch delay
Separate the Search for pokemon to Catch pokemon and to spam to find pokemon

**Comment by MikeTheShadow** [comment]
As of right now the catch delay is set to be humanized you can disable it with the realistic catch option I don't exactly see a need to modify it beyond what it is.
I don't understand your second question If you could maybe edit the current program in paint so you can better clarify thatd be great @goldenisadrian.

**Comment by goldenisadrian** [comment]
for version 1.5 I was running multiple instances of the bot where I'd have one account catching and the others spamming and the bot would still have the others trying to catch
I was thinking if that could be split into two options so one would spam and the other would be to enable catching

**Comment by MikeTheShadow** [comment]
If you want to make that kind of setup just make a few instances run with catch only whitelisted and then have no lists that should make them catch nothing. I'll probably add a catch option in the next update but I don't see it as being necessary for the average user.

**Comment by goldenisadrian** [comment]
also in this last update I can't start the bot anymore, it keeps telling me to fill out the settings
![1](https://user-images.githubusercontent.com/52621866/61029162-6cef1b80-a388-11e9-953a-6d2037a855d6.PNG)
![2](https://user-images.githubusercontent.com/52621866/61029175-711b3900-a388-11e9-922f-add84b2c16b4.PNG)

**Comment by MikeTheShadow** [comment]
Should be patched now. Here is a download link to the patched version http://bit.ly/2xEa35c

**Comment by zettu** [comment]
> 
> 
> Should be patched now. Here is a download link to the patched version (just download the latest ver)

when running the newest version i get this upon launch
![pokecrash](https://user-images.githubusercontent.com/52323898/61168694-0866c480-a520-11e9-95b6-b05bc75dbf4b.JPG)
I think something like this would be more useful than a single shut down time if it's not harder to implement 
![example](https://user-images.githubusercontent.com/52323898/61168707-3ba95380-a520-11e9-8e53-07b0b143dcc7.JPG)

**Comment by MikeTheShadow** [comment]
I'll probably add something like that in the next update but cleaner as for the crashing its because I hastily wrote the code for the pokemon leveler and I'm looking into fixing it. If anyone actually knows it works lemme know lol

**Comment by zettu** [comment]
> 
> 
> I'll probably add something like that in the next update but cleaner as for the crashing its because I hastily wrote the code for the pokemon leveler and I'm looking into fixing it. If anyone actually knows it works lemme know lol

Awesome, cleaner would be a lot better too lol. I can confirm it doesn't work. Why aren't you able to copy paste to/from the bot? Your bot is really coming along and i just wanted to say thank you again!
I haven't had an incorrect pokemon in ages

**Comment by MikeTheShadow** [comment]
Copy paste what @zettu

**Comment by zettu** [comment]
> 
> 
> Copy paste what @zettu

Anything, such as token. Also i just got the error that it's outdated and to download latest version. could you still allow the older versions to work even if you make a new version please

**Comment by MikeTheShadow** [comment]
You can copy/paste to the bot afaik

**Comment by zettu** [comment]
> 
> 
> You can copy/paste to the bot afaik
It doesn't give any options when you right click, I'm on windows 10.
I can confirm leveling still doesn't work, my pokemon got to 100 and didn't switch out

**Comment by goldenisadrian** [comment]
> > You can copy/paste to the bot afaik
> > It doesn't give any options when you right click, I'm on windows 10.
> > I can confirm leveling still doesn't work, my pokemon got to 100 and didn't switch out
> > also the leveling id list isn't scrollable i just have to go to the config file and add after i reach the bottom to be sure they're being added properly.

same for me maxes at 100 and doesn't switch

**Comment by MikeTheShadow** [comment]
Probably an error with my checking system I'll look into it

**Comment by zettu** [comment]
> 
> 
> Probably an error with my checking system I'll look into it

leveling doesn't work in most recent version also @MikeTheShadow

**Comment by MikeTheShadow** [comment]
Just to make sure you have pre selected a pokemon to level right @zettu ?

**Comment by zettu** [comment]
> 
> 
> Just to make sure you have pre selected a pokemon to level right @zettu ?

I'm not completely sure this is what you're asking but I had a pokemon to be leveled up selected when i started the bot and all the pokemon listed in the bot are not level 100. I sope that answers your question, sry!

**Comment by MikeTheShadow** [comment]
I'll apply a quick patch here

**Comment by MikeTheShadow** [comment]
Cant seem to p!info lol either I was banned or bots glitched

**Comment by zettu** [comment]
> 
> 
> Cant seem to p!info lol either I was banned or bots glitched

pokecord has been down a lot recently. i was curious if you're able to copy paste into the bot or if something is wrong on my end lol

**Comment by MikeTheShadow** [comment]
Using ctrl+v and ctrl+c you can copy paste things into the bot and with ctrl+a you can select the whole box
