### ISSUE TITLE
Not catching pokemon?

### ISSUE THREAD

**Issue by MikeTheShadow** [MikeTheShadow/PokeCordBot#26]
Okay so if you find that the bot is not catching anything please open a command prompt window in the folder and run the bot using the command: java -jar nameOfJar.jar
This will give a detailed analysis on what is going on and show errors in detail. Send a screenshot of the error it produces and paste it below thanks!

**Comment by xKeiR** [comment]
It's still not working
![bug](https://user-images.githubusercontent.com/11280310/61160305-44d5f880-a4ff-11e9-89aa-5e855afe35ca.jpg)

**Comment by MikeTheShadow** [comment]
Are you running it from source or the downloaded version @xKeiR ?

**Comment by xKeiR** [comment]
@MikeTheShadow Downloaded version

**Comment by MikeTheShadow** [comment]
This bug is caused by discord noticing the bot isn't a browser and blocking the bot from downloading the image. There is a simple solution but it's very impractical I'm gonna write up a quick test version for you try

**Comment by MikeTheShadow** [comment]
[replace your current pokebot with this](https://github.com/MikeTheShadow/PokeCordBot/files/3388128/PokeBot-1.0-all.zip)
@xKeiR Try this if it doesnt work try running as admin

**Comment by xKeiR** [comment]
There is still the same error :c

**Comment by MikeTheShadow** [comment]
okay try this one and you're running it as admin right? 
[PokeBot-1.0-all.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3388164/PokeBot-1.0-all.zip)

**Comment by xKeiR** [comment]
I have the same error. I am running it as administrator (I am running cmd as administrator and typing your command). Maybe I am doing something wrong.

**Comment by MikeTheShadow** [comment]
No it's definitely a problem I've seen hence this threads existence. I'm looking into it give me a few.

**Comment by MikeTheShadow** [comment]
Okay I think I have a solution try this one I rewrote the function @xKeiR 
[PokeBot-1.0-all.zip](https://github.com/MikeTheShadow/PokeCordBot/files/3388229/PokeBot-1.0-all.zip)

**Comment by xKeiR** [comment]
Oh nice! Now it's working. Thank you and congratulations!

**Comment by MikeTheShadow** [comment]
Okay closing this thread if some1 has a similar issue make a new one
