### ISSUE TITLE
Can't start be bot

### ISSUE THREAD

**Issue by Uravaok** [MikeTheShadow/PokeCordBot#27]
it sais that i need to fill out the settings tab when its filled 
![Anotación 2019-07-12 125004](https://user-images.githubusercontent.com/52445776/61123088-bb450d00-a4a3-11e9-8895-b7700e344589.png)
![Anotación 2019-07-12 125100](https://user-images.githubusercontent.com/52445776/61123090-bed89400-a4a3-11e9-8c29-754d02007094.png)

**Comment by MikeTheShadow** [comment]
Okay so this is def a bug I will be patching it soon right now you can bypass this by manually filling out the properties file @Uravaok I will close this thread when Ive patched it and released it

**Comment by MikeTheShadow** [comment]
Should be patched in 1.2.1
