### ISSUE TITLE
Accounts banned.

### ISSUE THREAD

**Issue by zettu** [MikeTheShadow/PokeCordBot#29]
Just curious if others had their dc accs banned.
I had 2 alts banned at same time, which is kind of weird considering one was newer

**Comment by zettu** [comment]
> 
> 
> Just curious if others had their dc accs banned.
> I had 2 alts banned at same time, which is kind of weird considering one was newer

apparently discords auto spam filters were triggered. Maybe adding multiple different messages to be sent and alternate as well as adding a configurable delay with randomization between 2 set points like 1.1-1.75 seconds or 1.25-1.6 would help mitigate dcs spam filter detection

**Comment by MikeTheShadow** [comment]
Yeah there is built in humanization. As for spam prevention I'll probably add something to change the timer but its already humanized so that it doesn't look too suspicious

**Comment by zettu** [comment]
> 
> 
> Yeah there is built in humanization. As for spam prevention I'll probably add something to change the timer but its already humanized so that it doesn't look too suspicious

What is the built in humanization?
do you think you'd be able to add multiple text phrases or that it would help? i feel that sending the same message 5000x may have been part of what triggered the detection lol.

**Comment by MikeTheShadow** [comment]
All my bots that I write contain a bit of randomness when a message is sent. I'll work on a randomness slider tomorrow so you can select a base delay time and add some modifications to how the custom message is sent. As for why you were banned it could also be that you're using multiple accounts and that triggered some red flags on the admins end (though I'm not sure) the next update will be a more security focused update tho.

**Comment by zettu** [comment]
> 
> 
> All my bots that I write contain a bit of randomness when a message is sent. I'll work on a randomness slider tomorrow so you can select a base delay time and add some modifications to how the custom message is sent. As for why you were banned it could also be that you're using multiple accounts and that triggered some red flags on the admins end (though I'm not sure) the next update will be a more security focused update tho.

The disable notification email said it was for spamming and i contacted them and they said it was specifically for spamming and that  even in a private server it's an issue. Definitely possible it has to do with multiple accounts but it didn't affect other some accs thankfully!

**Comment by MikeTheShadow** [comment]
I'll look into increasing the delay between messages def then

**Comment by zettu** [comment]
> 
> 
> I'll look into increasing the delay between messages def then

i feel like it had to do with the same message being sent so many times over and over too, which is why i think a rotating list of possible phrases to say would help prevent a ban. i know some other bots use this method too. your's is def the best though imo :D @MikeTheShadow

**Comment by MikeTheShadow** [comment]
Another reason your accounts got flagged was probably because they are new and then suddenly flooding discord with messages
