### ISSUE TITLE
Run PokeCordBot

### ISSUE THREAD

**Issue by RendyFox** [MikeTheShadow/PokeCordBot#30]
I dont know how to turn the bot on, im clicking on the "gradlew" file with and without admin and nothing happens, I can see the cmd for 0.5 sec and then it goes off.

**Comment by MikeTheShadow** [comment]
You're downloading the source code goto the readme and download the program from there

**Comment by RendyFox** [comment]
> You're downloading the source code goto the readme and download the program from there

Do I need to copy user Token or the channel Token?

**Comment by RendyFox** [comment]
I did it but it says Program crashed after i want to start it

**Comment by MikeTheShadow** [comment]
Afaik its broken but if you select a low level pokemon (less than level 100) then put pokemon ID's into the level list it should swap them out once they hit 100
