### ISSUE TITLE
cant start the bot

### ISSUE THREAD

**Issue by 72888hshu** [MikeTheShadow/PokeCordBot#31]
When I started the bot, it doesn't spam or catch.
![image](https://user-images.githubusercontent.com/48046222/61589776-ac680400-abe1-11e9-8b6a-fbc8ebe8f356.png)

**Comment by 72888hshu** [comment]
here was my settings
![image](https://user-images.githubusercontent.com/48046222/61589804-f355f980-abe1-11e9-8e8c-ca02c7674daf.png)

**Comment by 72888hshu** [comment]
so this time I restart it, first it gave me this error
![image](https://user-images.githubusercontent.com/48046222/61589851-973fa500-abe2-11e9-88d2-e5420f1bf9b6.png)

**Comment by MikeTheShadow** [comment]
Can you copy paste the entire error here for me or make a Pastebin for it it's kinda hard to break it down

**Comment by MadRougue** [comment]
is it possible to request for a video tutorial how to run the bot? i can't get it to start.

**Comment by MikeTheShadow** [comment]
@MadRougue sure I'll upload one tonight when I have the time

**Comment by MikeTheShadow** [comment]
https://www.youtube.com/watch?v=lo7YCg3UQ-4&feature=youtu.be @MadRougue
