### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RobertRitter99** [MikeTheShadow/PokeCordBot#34]
Paste: https://pastebin.com/1WnjyM7f
Please also leave me ur discord, skype steam or smth for fast contact.

**Comment by MikeTheShadow** [comment]
https://join.skype.com/invite/vPaWU6EeGED2 My skype if you want to chat with me

**Comment by Bl4zeman** [comment]
Got the same trouble, here is my pastebin : https://pastebin.com/FW3dbEVm

**Comment by MikeTheShadow** [comment]
@Bl4zeman your error seems to be due to an update with discord I'll look into it. If you're running it on your main acc make an alt and it should work.
