### ISSUE TITLE
Pokecord attempting to crack down on botters.

### ISSUE THREAD

**Issue by zettu** [MikeTheShadow/PokeCordBot#35]
Recently there was an announcement saying 2.5 million botted pokemon and 250 million credits were wipe and was curious if anyone using this has had it happen yet.
Also will there be changeable delays for spam in the future like there is for catching, it's definitely a nice feature!

**Comment by MikeTheShadow** [comment]
So uh yeah the current delay feature is for the spam and not for the catching :/ I kinda put it in the wrong spot and left it there

**Comment by zettu** [comment]
lolll kk didnt notice
