### ISSUE TITLE
"ı" issue

### ISSUE THREAD

**Issue by Hakuteiken3** [MikeTheShadow/PokeCordBot#36]
There is problem at catching pokes start with letter "ı". Like Inkay, Igglybuff. Pokecord Bot can't catch them and I don't know whether this problem applies all people or just people from Turkey.

**Comment by MikeTheShadow** [comment]
I've never seen this problem. Do the pokemon have the dotless i in them? Because if its language based if you can somehow get it to be english then it will catch them.

**Comment by Hakuteiken3** [comment]
> I've never seen this problem. Do the pokemon have the dotless i in them? Because if its language based if you can somehow get it to be english then it will catch them.

Yeah. There is seperate "ı" and "i" letters in Turkish alphabet. In English, maybet pressing "ı" writes "i" but in Turkish keyboards, it writes "ı" so they can't be caught.

Should I change pokemon photo names to try it?

**Comment by MikeTheShadow** [comment]
Does the bot say the correct i? Or do the pokemon names contain the wrong i?

**Comment by Hakuteiken3** [comment]
> Does the bot say the correct i? Or do the pokemon names contain the wrong i?

It should write "igglybuff, inkay, etc." but it writes "ınkay, ıgglybuff". My other friend had same problem too. He said that he changed the pokemon photo names from Inkay to İnkay but didn't work.

**Comment by MikeTheShadow** [comment]
İ is wrong if thats what he used it needs to be i. It could be due to the default keyboard layout on the PC but it's weird because it directly reads the names of the files and stores them in memory so if the name contains i it should send i not ı

**Comment by Hakuteiken3** [comment]
> İ is wrong if thats what he used it needs to be i. It could be due to the default keyboard layout on the PC but it's weird because it directly reads the names of the files and stores them in memory so if the name contains i it should send i not ı

![IMG_3701__41012 1461348319 1280 1280](https://user-images.githubusercontent.com/54886704/64290216-57543780-cf6e-11e9-99db-7ea57da0dc39.jpg)

English keyboards have one "I" and it registers as "i" if you write without Caps Lock but Turkish keyboard take "I" as "I" with caps lock and "ı" without caps lock. We have "i" for writing lower case "i" and upper case"İ" 

Maybe that's the problem.

**Comment by MikeTheShadow** [comment]
I'll add an extra debug feature that will print all content to the console. But it's still confusing because unless the PC renames the files automatically it should work.

**Comment by Hakuteiken3** [comment]
> I'll add an extra debug feature that will print all content to the console. But it's still confusing because unless the PC renames the files automatically it should work.

Sorry for causing extra work.

When I use pokecord info command, "info Inkay, info inkay and even using Turkish upper case letter İ works (like info İnkay) but lower case ınkay (which bot writes) doesn't work.

And all pokemon photo names starts with capital letter but bot makes them lower case at Discord.

**Comment by MikeTheShadow** [comment]
I'll write a custom version for you that solves this problem. I don't want it on the main build due to anticheat

**Comment by MikeTheShadow** [comment]
Download the latest version and replace the jar with this custom one see if it works. All thats changed is that it capitalizes everything it sends for catching
[CUSTOMBUILD](https://github.com/MikeTheShadow/PokeCordBot/files/3577095/CUSTOMBUILD.zip)

**Comment by Hakuteiken3** [comment]
> Download the latest version and replace the jar with this custom one see if it works. All thats changed is that it capitalizes everything it sends for catching
> [CUSTOMBUILD](https://github.com/MikeTheShadow/PokeCordBot/files/3577095/CUSTOMBUILD.zip)

It makes every letter upper case. It's too much work for you. Sorry for trouble.

**Comment by Hakuteiken3** [comment]
> Download the latest version and replace the jar with this custom one see if it works. All thats changed is that it capitalizes everything it sends for catching
> [CUSTOMBUILD](https://github.com/MikeTheShadow/PokeCordBot/files/3577095/CUSTOMBUILD.zip)

Since your custom build work (because all upper case letters), I tried naming pokemon photo names and using lower case ı with Turkish version work. 

Sorry for custom build that I make you compile.
