### ISSUE TITLE
Can't auto catch pokes that some servers spawns with smaller photos

### ISSUE THREAD

**Issue by Hakuteiken3** [MikeTheShadow/PokeCordBot#39]
Bot can't auto catch pokes that some servers spawns with smaller photos:

![2019-09-07_23-04-09](https://user-images.githubusercontent.com/54886704/64479754-f32ab100-d1c3-11e9-92a2-75368136bb36.png)

Is this issue can be solved or we should use it on serves that spawns with large photos?

**Comment by MikeTheShadow** [comment]
As my bot does not have an index of those pokemon photos it does not. I could maybe create another bigger dex for it but idk if it'd be worth it performance wise as the bot would slow down quite a bit.

**Comment by MikeTheShadow** [comment]
If you really want me to. Collect them send me about 5-10 of the images and I'll see if I can make you a custom dex.

**Comment by Hakuteiken3** [comment]
> If you really want me to. Collect them send me about 5-10 of the images and I'll see if I can make you a custom dex.

It's no problem :) Just asked. There are more serves with spawning with bigger photos.
