### ISSUE TITLE
Whitelists don't work

### ISSUE THREAD

**Issue by Hakuteiken3** [MikeTheShadow/PokeCordBot#40]
I created other list named uncaught and put it in the folder. I select "Catch Whitelisted" but nothing happened while Arceus spawned.

**Comment by MikeTheShadow** [comment]
Did the bot say it loaded the list with the correct amount of pokemon? Also I just added Arceus to the default list so it will be in the next patch?

**Comment by Hakuteiken3** [comment]
> Did the bot say it loaded the list with the correct amount of pokemon? Also I just added Arceus to the default list so it will be in the next patch.

Yeah, and also I saw Arceus in poke pictures and I thought whitelist was the problem. If it's not you or I can close the topic :D

**Comment by MikeTheShadow** [comment]
send me the list you made if you don't mind

**Comment by Hakuteiken3** [comment]
[uncaught.list.txt](https://github.com/MikeTheShadow/PokeCordBot/files/3590971/uncaught.list.txt)
That's the one. Its list form is in the lists folder.

![Arceus](https://user-images.githubusercontent.com/54886704/64538876-19686200-d326-11e9-9a14-62775a0ad4ad.jpg)
Also, Arceus is in pokedex folder.

**Comment by MikeTheShadow** [comment]
theres your problem its uncaught.list.txt you need to remove the .txt. To do this 
![image](https://user-images.githubusercontent.com/18271009/64539264-6d9a2480-d2db-11e9-9c19-0d60feb9629c.png)

check the box that says file name extensions and remove the .txt so its just .list and it should work

**Comment by Hakuteiken3** [comment]
> theres your problem its uncaught.list.txt you need to remove the .txt. To do this
> ![image](https://user-images.githubusercontent.com/18271009/64539264-6d9a2480-d2db-11e9-9c19-0d60feb9629c.png)
> 
> check the box that says file name extensions and remove the .txt so its just .list and it should work

It's because you can't send "lists" files to github. That's why I wrote it to notepad exactly how it is in lists file.

**Comment by MikeTheShadow** [comment]
I see

**Comment by MikeTheShadow** [comment]
looking into it now

**Comment by MikeTheShadow** [comment]
Fixed in latest build
