### ISSUE TITLE
Prefix issue

### ISSUE THREAD

**Issue by zettu** [MikeTheShadow/PokeCordBot#43]
When starting the bot it does p!info (i think to check your pokemon for level?) but the issue is my prefix is . so it's not setting the correct prefix for this check. I'm not sure that's explained well, sorry lol

**Comment by MikeTheShadow** [comment]
Found it lol. It will be fixed in the next update but I probably want to add a new feature before then it might take a while.

**Comment by MikeTheShadow** [comment]
Fixed
