### ISSUE TITLE
Catching pokes without spam still doesn't work after fixing "catching system"

### ISSUE THREAD

**Issue by Hakuteiken3** [MikeTheShadow/PokeCordBot#44]
Lists doesn't work again.

1-2 days ago, it recognized my Alolan list and caught one Alolan.

Also, it caught 2 of pokes in my uncaught list, too.

**Comment by Hakuteiken3** [comment]
> There's only two possibilities.
> 
> 1. The spacing in the dat file is wrong in that case I'd have to patch it.
> 2. Something is wrong on the text end which is more likely since I've run multiple dat file tests and everything seemed normal

Well, there is no spacing at legendaries list so I don't know what's the problem.

**Comment by MikeTheShadow** [comment]
See thats where I'm finding it confusing. Since I just checked the spacing in the dat file and it returned nominal
![image](https://user-images.githubusercontent.com/18271009/64898541-bc7dec00-d644-11e9-84ea-f5b03380b98d.png)
I'll need to attach some more intense debugging tools ig to the main build.

**Comment by MikeTheShadow** [comment]
I added a better debug system. The bot now tells you everything that it sees so if it doesn't see it thats a whole other problem. It could be that the internet bugged out or something was wrong with the file. Use issue number #48 to help you.

**Comment by Hakuteiken3** [comment]
> I added a better debug system. The bot now tells you everything that it sees so if it doesn't see it thats a whole other problem. It could be that the internet bugged out or something was wrong with the file. Use issue number #48 to help you.

When I use the bot at my server with spamming, it can find and catch all pokemons but when I use it without spamming at other servers, it can't recognize the spawns.

There is nothing written in debug window when not using spam.

**Comment by Hakuteiken3** [comment]
![Ek Açıklama 2019-09-14 114818](https://user-images.githubusercontent.com/54886704/64905765-a96f2880-d6e5-11e9-9c34-11f9da143941.png)

I started bot on one server. Nothing happened after [JDA MainWS-ReadThread] INFO JDA - Finished Loading!

![Ek Açıklama 2019-09-14 114238](https://user-images.githubusercontent.com/54886704/64905782-d15e8c00-d6e5-11e9-9a42-10813240e802.png)

Here is another screenshot after try starting - stopping and starting it multiple times.

**Comment by Hakuteiken3** [comment]
For example, Alakazam was on my uncaught list and I couldn't catch it while I was not spamming in other computer. Now, I caught it with spamming and without using whitelist.

**Comment by MikeTheShadow** [comment]
Hmmmm. Looking into it now but I can't seem to pinpoint an exact bug

**Comment by Hakuteiken3** [comment]
> Hmmmm. Looking into it now but I can't seem to pinpoint an exact bug

One time, gulpin spawned and I caught it by writing it and Fearow spawned. When I try writing p!catch fearow, bot wrote "p!catch gulpin" after next spawn and 30 second later.

**Comment by MikeTheShadow** [comment]
It has a delay automatically built-in as well as the ability to catch multiple pokemon at the same time.

**Comment by Hakuteiken3** [comment]
> It has a delay automatically built-in as well as the ability to catch multiple pokemon at the same time.

Well, it didn't recognized fearow and it recognized gulpin 30-40 seconds later. It can't catch the old spawn after new spawn, Pokecord bot doesn't allow it.

**Comment by Hakuteiken3** [comment]
> It has a delay automatically built-in as well as the ability to catch multiple pokemon at the same time.

Also, I started the bot again and it found one pokemon. Then, it stopped working again.

**Comment by Hakuteiken3** [comment]
@MikeTheShadow 

[JDA MainWS-ReadThread] INFO WebSocketClient - Connected to WebSocket
DEBUG pokemonFound: audino
DEBUG pokemonFound: mareanie
DEBUG pokemonFound: carvanha
[JDA MainWS-ReadThread] INFO JDA - Finished Loading!

It worked between INFO WebSocket Client and INFO JDA and caught Maeranie and stop recognizing pokes after INFO JDA - Finished loading.

**Comment by MikeTheShadow** [comment]
I can't seem to reproduce this problem.

**Comment by Hakuteiken3** [comment]
> I can't seem to reproduce this problem.

:(

**Comment by Hakuteiken3** [comment]
> I can't seem to reproduce this problem.

Sometimes, it finds pokemon between [JDA MainWS-ReadThread] INFO WebSocketClient - Connected to WebSocket and [JDA MainWS-ReadThread] INFO JDA - Finished Loading!

![Ek Açıklama 2019-09-16 064620](https://user-images.githubusercontent.com/54886704/64933379-b9098100-d84d-11e9-94aa-4d2258304b58.png)

Could it be related to this nullpointer exception error?

**Comment by Hakuteiken3** [comment]
> I can't seem to reproduce this problem.

Also, when I spam at private servers, debug can find pokemon names from servers that bot doesn't work without spam.

**Comment by Hakuteiken3** [comment]
> I can't seem to reproduce this problem.

I tried the bot at my work computer and same problem. It can't catch pokes without spamming.

**Comment by MikeTheShadow** [comment]
Unless that nullpointer is spammed it's really irrelevant. I'll run some tests when I get home

**Comment by Hakuteiken3** [comment]
> Unless that nullpointer is spammed it's really irrelevant. I'll run some tests when I get home

Since it doesn't work without spam, I'm doing it with 10 second delayed spam lol :D

**Comment by Hakuteiken3** [comment]
@MikeTheShadow 

Catching pokes without spam still doesn't work after fixing "catching system". I don't know why and whether others have same problem.

**Comment by MikeTheShadow** [comment]
Patched in https://github.com/MikeTheShadow/PokeCordBot/releases/tag/V1.4.4-beta.1
