### ISSUE TITLE
[ERROR] java.lang.OutOfMemoryError: Java heap space 

### ISSUE THREAD

**Issue by Hakuteiken3** [MikeTheShadow/PokeCordBot#47]
This error is shown when I start the bot. I triend on different 2 PCs and I get same error.

![Ek Açıklama 2019-09-13 102528](https://user-images.githubusercontent.com/54886704/64848934-f4703980-d61a-11e9-966e-5c293f17e2a4.png)
![Ek Açıklama 2019-09-13 102334](https://user-images.githubusercontent.com/54886704/64848935-f4703980-d61a-11e9-81d0-2a91c8007adb.png)

 - OS: Windows 7 & 10
 - Browser: Google Chrome & Google Chrome Portable
 - Version: Latest Versions

**Comment by MikeTheShadow** [comment]
I guess I should specify a few things in the bug report.
1. How much ram does your computer  have
2. What version of java (64/32bit)

**Comment by Hakuteiken3** [comment]
> I guess I should specify a few things in the bug report.
> 
> 1. How much ram does your computer  have
> 2. What version of java (64/32bit)

8 GB - Both computers. It interesting since I used the bot at 2 PCs for 2-3 weeks until today, both of them. 

Revo Uninstaller says that 32 bit. Should I uninstall it and install 64 bit one?

**Comment by MikeTheShadow** [comment]
yes 32bit limits the amount of ram you get to use that should fix the error though I am upset that it's using that much ram

**Comment by Hakuteiken3** [comment]
> yes 32bit limits the amount of ram you get to use that should fix the error though I am upset that it's using that much ram

I haven't used something related to java for years lol. I didn't know I had one until I started using your bot.

**Comment by Hakuteiken3** [comment]
> yes 32bit limits the amount of ram you get to use that should fix the error though I am upset that it's using that much ram

Worked like a charm.
