### ISSUE TITLE
[SUGGESTION] Add this list of shiny Pokemon to the directory

### ISSUE THREAD

**Issue by Vipth** [MikeTheShadow/PokeCordBot#52]
I created a complete list of Shiny pokemon, and I think it would be really useful for others if it was added to the default lists when you download the bot.

**Shinies List**
https://pastebin.com/K5KZCrPT

**Comment by MikeTheShadow** [comment]
Correct me if I'm wrong but last time I checked you don't know you caught a shiny until you actually type the catch command?

**Comment by Vipth** [comment]
> Correct me if I'm wrong but last time I checked you don't know you caught a shiny until you actually type the catch command?

Yeah, you're right. I was unaware you didn't know the pokemon was a shiny until you caught it.
