### ISSUE TITLE
[BUG] [ERROR] Bot doesn't work and there are no specific errors

### ISSUE THREAD

**Issue by Hakuteiken3** [MikeTheShadow/PokeCordBot#53]
Spam feature is broken with "Error understanding sentence" error. Also, it shows poke IVs on Debug CMD.

**Screenshots**
![Ekran Alıntısı](https://user-images.githubusercontent.com/54886704/66912516-658c7d80-f01b-11e9-8f57-11478247d2b6.PNG)

**Desktop**
 - OS: Windows 7
 - Browser: Chrome
 - Version: 77

**Comment by Hakuteiken3** [comment]
> Yeah, that's to be expected. I made it so the debug tool outputs a lot more. While this complicates things it was necessary to make sure that the catch feature works

Technically, it gives same error on "run" too. I tried run first and when I saw that spam was not working, used debug.

**Comment by MikeTheShadow** [comment]
Spam works for me? if it's not giving an error I'd need to see your settings to be able to tell

**Comment by Hakuteiken3** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/54886704/66936039-ba44ee00-f045-11e9-9b6d-59ad899b2a5c.PNG)

**Comment by MikeTheShadow** [comment]
The latest build that I just released?

**Comment by Hakuteiken3** [comment]
> The latest build that I just released?

1.4.3 wasn't working, I tried 1.4.4 and still nothing.

**Comment by MikeTheShadow** [comment]
have you tried clearing the spam box and just putting in a single character? As well as making sure that the channel ID is correct?

**Comment by MikeTheShadow** [comment]
![image](https://user-images.githubusercontent.com/18271009/66936987-e20f6400-effb-11e9-9770-3cb4bf43fd01.png)
It's working for me. Catching Spamming and everything

**Comment by Hakuteiken3** [comment]
> ![image](https://user-images.githubusercontent.com/18271009/66936987-e20f6400-effb-11e9-9770-3cb4bf43fd01.png)
> It's working for me. Catching Spamming and everything

It wasn't showing IVs and duel outcomes before. Did you add them or something happened to mine?

**Comment by Hakuteiken3** [comment]
> That's just the debug line doing its thing. That error is irrelevant and only exists to help incase the catching breaks again.

Wasn't there one more step after "Connected to websocket"?

**Comment by MikeTheShadow** [comment]
and not afaik

**Comment by MikeTheShadow** [comment]
https://github.com/MikeTheShadow/PokeCordBot/releases/tag/V1.4.4-beta.2 Try this build

**Comment by Hakuteiken3** [comment]
> https://github.com/MikeTheShadow/PokeCordBot/releases/tag/V1.4.4-beta.2 Try this build

I'm trying it but still doesn't work. Still, no errors except some nullpointer exception

**Comment by MikeTheShadow** [comment]
send me a screenshot of the folder its running in, please

**Comment by Hakuteiken3** [comment]
> send me a screenshot of the folder its running in, please

![Ek Açıklama 2019-10-16 200449](https://user-images.githubusercontent.com/54886704/66941763-4c51f400-f050-11e9-87a1-5f258fd76e5c.png)

It's on desktop. It worked before "New IV showing commands"

**Comment by MikeTheShadow** [comment]
and I'm guessing that you put it in a new folder with a new pokedex and Lists etc?

**Comment by Hakuteiken3** [comment]
> and I'm guessing that you put it in a new folder with a new pokedex and Lists etc?

Yeah, I'm on different computer and I deleted old one. I downloaded necessary files. 

On other computer, I changed jar file only and I have same problem.

**Comment by MikeTheShadow** [comment]
Are you sure you have the right channel ID?

**Comment by Hakuteiken3** [comment]
> Are you sure you have the right channel ID?

Of course. I tried different channels in different servers. Nothing works.

**Comment by MikeTheShadow** [comment]
Weird it's working on my end on every comp so far.

**Comment by Hakuteiken3** [comment]
> Weird it's working on my end on every comp so far.

Well, not for me lol. Wondering what happened. Spam was working even when auto catch was broken.

**Comment by MikeTheShadow** [comment]
and you logged into the account and manually can do everything?

**Comment by Hakuteiken3** [comment]
> and you logged into the account and manually can do everything?

Yes. Also, other bot works, too. (Which uses codes in txt files to catch pokes)

**Comment by MikeTheShadow** [comment]
![image](https://user-images.githubusercontent.com/18271009/67018916-244aab00-f0b9-11e9-8444-f398cc52f19f.png)
Works on a new PC. Just caught something too

**Comment by MikeTheShadow** [comment]
Hmmm. It's really confusing since it should have no troubles. Send me a screen of the minimum Settings you're using

**Comment by Hakuteiken3** [comment]
> Hmmm. It's really confusing since it should have no troubles. Send me a screen of the minimum Settings you're using

I'm confused, too lol. Which settings you want?

**Comment by Hakuteiken3** [comment]
> Hmmm. It's really confusing since it should have no troubles. Send me a screen of the minimum Settings you're using

It's because having lots of Discord servers, big ones especially.
